# Creating Tensors: Random

In [2]:
import tensorflow as tf

In [10]:
seedVal = 42
firstGenerator = tf.random.Generator.from_seed(seedVal)
firstGenerator

In [11]:
randomTensorOne = firstGenerator.normal(shape=(3,2))
randomTensorOne

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
randomTensorTwo = firstGenerator.normal(shape=(3,2))
randomTensorTwo

# NOT EQUAL
randomTensorTwo == randomTensorOne



# equal...hmm!
secondVar = tf.random.Generator.from_seed(42)
secondVar = secondVar.normal(shape=(3,2))
secondVar == randomTensorOne

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Docs
- [random](https://www.tensorflow.org/api_docs/python/tf/random): make random things
- [random.Generator](https://www.tensorflow.org/api_docs/python/tf/random/Generator): a random number generator
- [generator.normal](https://www.tensorflow.org/api_docs/python/tf/random/Generator#normal): create random values from a **normal distribution**