<a href="https://colab.research.google.com/github/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow: An Intro
[TensorFlow](https://www.tensorflow.org/): an open-source end-to-end machine learning library useful for things like data "wrangling", modelling, building machine-learning models, and more.

Rather than building machine learning and deep learning models from "scratch",  tensorflow contains many of the most common machine learning functions you'll want to use.

## Goals
- creating tensors
- Getting information from tensors
- Manipulating tensors
- Comparing & Combining Tensorflow, Tensors, and NumPy
- Using `@tf.function` as a way to speed up Python functions
- Using GPUs with TensorFlow

## Imports

In [46]:
import datetime
import numpy as np
import tensorflow as tf
print(f'tensorlfow version: {tf.__version__}') # find the version number (should be 2.x+)

tensorlfow version: 2.12.0


## Tensors

### Like Numpy Arrays
NumPy arrays are similar to [tensors](https://www.tensorflow.org/guide/tensor). One major difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensorflow (_and tensors_) can be used & processed on [GPUs (graphical processing units)](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) and [TPUs (tensor processing units)](https://en.wikipedia.org/wiki/Tensor_processing_unit). One benefit of being able to run on GPUs and TPUs is faster computation. GPUs and TPUs will process data faster than CPUs.  

Tensors are like multi-dimensional numerical representations (also referred to as n-dimensional, where n can be any number) of _things_:
- numbers themselves, using tensors to represent the price of houses)
- images, using tensors to represent the pixels of an image)
- text, using tensors to represent words

## Working With Tensors

### Creating Tensors with `tf.constant()`
Creating tensors, "from scratch", may not be common. TensorFlow has modules built-in (such as [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) and [`tf.data`](https://www.tensorflow.org/guide/data)) which are able to read input data sources and _automatically convert them to tensors_. Here, though, a look at creating tensors with [`tf.constant()`](https://www.tensorflow.org/api_docs/python/tf/constant).  

A scalar is known as a "rank 0" tensor. Scalars have no dimensions - just a single number.

By default, TensorFlow creates tensors with either an `int32` or `float32` datatype.

This is known as [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science) (the higher the number, the more precise the number, the more space it takes up on your computer).

There are different types of numbers and number datatypes:
* **scalar**: a single number.
* **vector**: a number with direction (e.g. wind speed with direction).
* **matrix**: a 2-dimensional array of numbers.
* **tensor**: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector). 

"Matrix" and "Tensor" may be used interchangably.

For more on the mathematical difference between scalars, vectors and matrices see the [visual algebra post by Math is Fun](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html).

#### Scalar

In [8]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
print(f'scalar tensor: {scalar}')
scalar

scalar tensor: 7


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

#### Vector

In [10]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [15]:
# Check the number of dimensions of our vector tensor
vector.ndim

1

#### Matrix

In [14]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [17]:
matrix.ndim

2

In [18]:
# Create another matrix and define the datatype
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [21]:
# Even though another_matrix contains more numbers than matrix, its 'ndim' (dimension count) is the same:
another_matrix.ndim

2

In [23]:
# How about a tensor with more than 2 dimensions
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### On Tensor Dimensions
This tensor is known as a rank 3 tensor (3-dimensions):
```python
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
```

### Dimension Count from Source Data
<!-- with shape (224, 224, 3, 32), where: -->
Tensors may be created based on a series of images:
* image-width of 224
* image-height of 224
* 3 color channels: (red, green blue)
* instruct tensorflow to process 32 images at-a-time, in a "batch" of 32
That tensor might have a shape (224, 224, 3, 32)

## Creating Tensors with `tf.Variable()`

Often, when working with data, tensors are created automatically. Here, creating tensors using [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

### Constants are Immutable, Variables are mutable
The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).  

To change an element of a `tf.Variable()` tensor requires the `assign()` method.

In [27]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [32]:
# 
# FAILING at changing a Variable  without ".assign()"
# 
# Will error (requires the .assign() method)
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [33]:
# 
# Success changing a tensor
# 
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [34]:
# 
# FAILURE attemtpting to change a constant tensor
# 
unchangeable_tensor[0].assign(7)
unchangleable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

Why would you want to create random tensors? 

Random tensors are what neural networks use to **intialize their weights** when recognizing (patterns) in data. The process of a neural network learning might often involve taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

<!-- **How a network learns** -->
<!-- ![how a network learns](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png) -->
<!-- *A network learns by starting with random patterns (1) then going through demonstrative examples of data (2) whilst trying to update its random patterns to represent the examples (3).*
 -->
Here, creating random tensors by using the [`tf.random.Generator`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class) class.

In [36]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
print(random_1)
print(random_2)
print(f'random_1 == random_2: {random_1 == random_2}')

tf.Tensor(
[[-0.75658023 -0.06854693]
 [ 0.07595028 -1.2573844 ]
 [-0.23193759 -1.8107857 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.75658023 -0.06854693]
 [ 0.07595028 -1.2573844 ]
 [-0.23193759 -1.8107857 ]], shape=(3, 2), dtype=float32)
random_1 == random_2: [[ True  True]
 [ True  True]
 [ True  True]]


The random tensors here are [pseudorandom numbers](https://www.computerhope.com/jargon/p/pseudo-random.htm) (they appear as random, but really aren't). Once a seed is set,tensorflow will generate the same random numbers. 

In [38]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
# Are they equal?
print(random_3)
print(random_4)
print(f'random_3 == random_4: {random_3 == random_4}')

tf.Tensor(
[[-0.75658023 -0.06854693]
 [ 0.07595028 -1.2573844 ]
 [-0.23193759 -1.8107857 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.27305746 -0.29925638]
 [-0.36523244  0.61883324]
 [-1.0130817   0.28291693]], shape=(3, 2), dtype=float32)
random_3 == random_4: [[False False]
 [False False]
 [False False]]


## Shuffling Tensors

In [39]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [40]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Rule #4 of the [`tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) documentation says that

> "4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

`tf.random.set_seed(42)` sets the global seed, and the `seed` parameter in `tf.random.shuffle(seed=42)` sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."


In [41]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [42]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

## Other ways to make tensors

- [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones) will create a tensor of all ones 
- [`tf.zeros()`](https://www.tensorflow.org/api_docs/python/tf/zeros) will create a tensor of all zeros

In [43]:
# Make a tensor of all ones
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [44]:
# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [25]:
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Getting information from tensors
### Attributes
Common bits to get about a tensor:
* **Shape:** The length (number of elements) of each of the dimensions of a tensor
* **Rank:** The number of tensor dimensions:
  * A scalar has rank 0
  * a vector has rank 1
  * a matrix is rank 2
  * a tensor has rank `n`
* **Axis** or **Dimension:** A particular dimension of a tensor
* **Size:** The total number of items in the tensor

These might be especially useful when trying to organize the shapes of input data to inform/match the shapes of a model. I.E, , making sure the shape of image tensors are the same shape as a models input layer.

In [47]:
# Create a rank 4 tensor (4 dimensions)
rootDim = 2
nestedOneDim = 3
nestedTwoDim = 4
nestedThreeDim = 5
rank_4_tensor = tf.zeros([rootDim, nestedOneDim, nestedTwoDim, nestedThreeDim])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [48]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [54]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Items by index

In [50]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [57]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [59]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

## Manipulating tensors (tensor operations)

Finding patterns in tensors (numberical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

###  Add A Dimension with newaxis and expanddims
Add dimensions to a tensor whilst keeping the same information present using `tf.newaxis`
- [newaxis](https://www.tensorflow.org/api_docs/python/tf/Tensor#some_useful_examples)
- [expand_dims](https://www.tensorflow.org/api_docs/python/tf/expand_dims)

In [60]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
print('---- rank_2_tensor ----')
print(rank_2_tensor)
print('---- rank_3_tensor ----')
print(rank_3_tensor)

---- rank_2_tensor ----
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
---- rank_3_tensor ----
tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]], shape=(2, 2, 1), dtype=int32)


In [61]:
# 
# expand_dims
# 
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Add
Here, creating a tensor with `tf.constant()`, adding 10, and seeing that the original tensor is unchanged (the addition gets done on a copy).

In [63]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
print(tensor + 10)
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


### Multiply

In [66]:
print(tensor * 10)

# Use the tensorflow function equivalent of the '*' (multiply) operator
print(tf.multiply(tensor, 10))

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


### Subtract

In [65]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

## Matrix mutliplication
> 🔑 **Note:** '`@`' in Python is the symbol for matrix multiplication.

One of the most common operations in machine learning algorithms is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

TensorFlow implements this matrix multiplication functionality in the [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) method.

The main two rules for matrix multiplication to remember are:
1. The inner dimensions of the two matrixes must match:
  * `(3, 5) @ (3, 5)` won't work
  * `(5, 3) @ (3, 5)` will work
  * `(3, 5) @ (5, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
 * `(5, 3) @ (3, 5)` -> `(5, 5)`
 * `(3, 5) @ (5, 3)` -> `(3, 3)`

In [69]:
# Matrix multiplication in TensorFlow
print('TENSOR--------')
print(tensor)
print('----tensor MULTIPLIED----')
tf.matmul(tensor, tensor)

TENSOR--------
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
----tensor MULTIPLIED----


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Multiplying with mismatched shapes

In [70]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [72]:
# 
# see the error
# 
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

Trying to matrix multiply two tensors with the shape `(3, 2)` errors because the inner dimensions don't match.

We need to either:
* Reshape X to `(2, 3)` so it's `(2, 3) @ (3, 2)`.
* Reshape Y to `(3, 2)` so it's `(3, 2) @ (2, 3)`.


## Reshaping Matrixes
Reshaping can be done with either:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - reshape a tensor into a defined shape
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - changes the dimensions of a given tensor

### Reshape

In [74]:
# Example of reshape (3, 2) -> (2, 3)
print('-----Y----')
print(Y)
print('-----Y reshaped----')
tf.reshape(Y, shape=(2, 3))

-----Y----
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
-----Y reshaped----


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [76]:
# 
# NOW multiplying X & Y works
# 
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

### Transpose

In [78]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [79]:
# 
# NOW multiplying X & Y will work
# 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### with matmul arguments

In [48]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Notice the difference in the resulting shapes when tranposing `X` or reshaping `Y`.
Machine-Learning Engineers & those working in neural-networks may spend a bunch of time reshaping data (in the form of tensors) to prepare it to be used with various operations (such as feeding it to a model).

### The dot product

Multiplying matrices by eachother is also referred to as the dot product.

### tensordot
You can perform the `tf.matmul()` operation using [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot). 

In [49]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Comparing reshape & transpose
These two get different results.

In [80]:
# 
# transposing Y
# 
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [81]:
# 
# reshaping Y 
# 
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [86]:
# Inspecting shapes of Y comparing reshaing methods

print(f'Y.shape: {Y.shape}')
print(f'Y.reshape: {tf.reshape(Y, (2, 3)).shape}')
print(f'Y.transpose: {tf.transpose(Y).shape}')

Y.shape: (3, 2)
Y.reshape: (2, 3)
Y.transpose: (2, 3)


In [88]:
# Check values of Y, reshape Y and tranposed Y
print("Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


The different results could be explained:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the [`perm` parameter](https://www.tensorflow.org/api_docs/python/tf/transpose).

So which should you use?

Not Sure...

#### references, and examples
* If we transposed `Y`, it would be represented as $\mathbf{Y}^\mathsf{T}$ (note the capital T for tranpose).
* Get an illustrative view of matrix multiplication [by Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html).
* Try a hands-on demo of matrix multiplcation: http://matrixmultiplication.xyz/ (shown below).

![visual demo of matrix multiplication](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-matrix-multiply-crop.gif)

## Changing the datatype of a tensor

This is common when a goal is to using less precision to reduce computation energy (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers), because with less bits comes less space that the computations requires.

Here, changing the datatype of tensors using [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).

In [91]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
print(f'B.dtype: {B.dtype}')
print(f'C.dtype: {C.dtype}')

B.dtype: <dtype: 'float32'>
C.dtype: <dtype: 'int32'>


In [92]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
print(f'B.dtype: {B.dtype}')

B.dtype: <dtype: 'float16'>


In [93]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
print(f'C.dtype: {C.dtype}')

C.dtype: <dtype: 'float32'>


## Getting the absolute value
Here, using [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).

In [96]:
# Create tensor with negative values
D = tf.constant([-7, -10])
print(D)
# Get the absolute values
print(f'abs values: {tf.abs(D)}')

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)
abs values: [ 7 10]


## Stats: min, max, mean, sum (aggregation)
To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.

**Note:** typically, each of these is under the `math` module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.

In [97]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 9, 59, 17, 71, 80, 21, 65, 22, 70, 87, 33, 31, 22, 32,  8, 62, 62,
       79, 30, 27,  4, 31, 22, 59, 45, 64,  7, 26, 54, 30, 67, 85, 33, 55,
       41, 79, 98, 65, 59, 61, 57, 13, 14, 53, 81, 78, 55, 80, 43, 84])>

In [98]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [99]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [100]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [101]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2430>

Also available are the standard deviation ([`tf.reduce_std()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_std)) and variance ([`tf.reduce_variance()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance)).

### Finding the positional maximum and minimum
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - find the position of the maximum element in a given tensor.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - find the position of the minimum element in a given tensor.

In [102]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.7647888 , 0.56895957, 0.05056721, 0.19468096, 0.97438256,
       0.09067676, 0.55055159, 0.77230744, 0.47620834, 0.7719471 ,
       0.25394192, 0.41012713, 0.35539614, 0.7684867 , 0.63143059,
       0.4101147 , 0.43091275, 0.57055221, 0.00929904, 0.74952705,
       0.29288867, 0.58413887, 0.11442201, 0.22658184, 0.89060412,
       0.11438289, 0.68534446, 0.4922785 , 0.26824488, 0.62954618,
       0.20132858, 0.20327259, 0.91980501, 0.83596987, 0.15349621,
       0.00924867, 0.59771575, 0.74226613, 0.23884987, 0.17713875,
       0.81237591, 0.48005606, 0.91516802, 0.8283424 , 0.06389213,
       0.50454878, 0.5046474 , 0.05294236, 0.14747612, 0.05856524])>

In [109]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [110]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [114]:
# Find the maximum element position of F
print(f"The maximum value of F is {tf.reduce_max(F).numpy()} at position: {tf.argmax(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is 0.9743825645238031 at position: 4
Using tf.argmax() to index F, the maximum value of F is: 0.9743825645238031
Are the two max values the same? True


## Squeezing a tensor (removing all single dimensions)
* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.


In [116]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
print(G.shape)
print(G.ndim)

(1, 1, 1, 1, 50)
5


In [118]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
print(G_squeezed.shape)
print(G_squeezed.ndim)

(50,)
1


## One-hot encoding
[`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot)

In [123]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
print(tf.one_hot(some_list, depth=len(some_list)))
print(tf.one_hot(some_list, depth=len(some_list) - 2))

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)


In [127]:
# Specify a custom one-hot values for on and off encoding
on="ON"
off="-"
tf.one_hot(some_list, depth=4, on_value=on, off_value=off)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'-', b'-', b'-'],
       [b'-', b'ON', b'-', b'-'],
       [b'-', b'-', b'ON', b'-'],
       [b'-', b'-', b'-', b'ON']], dtype=object)>

## Squaring, log, square root
* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) - get the square of every value in a tensor. 
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) - get the squareroot of every value in a tensor (**note:** the elements need to be floats or this will error).
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) - get the natural log of every value in a tensor (elements need to floats).

In [130]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
print(H)
H

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int64)


<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [136]:
# 
# Square
# 
tf.square(H)

# 
# sqrt 
# 
# shows error
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [137]:
# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [138]:
# Find the square root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [140]:
# 
# log (input also needs to be float)
# 
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Manipulating `tf.Variable` tensors
Change tensors in-place with
* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - assign a different value to a particular index of a variable tensor
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - add to an existing value and reassign it at a particular index of a variable tensor


In [148]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
print('I:')
print(I)

# 
# Assign the final value a new value of 50
# 
print('I.assing...')
print(I.assign([0, 1, 2, 3, 50]))

# NOTE: no copy made, the "original" gets the update
print('I again')
print(I)

# 
# 
#
# Add 10 to every element in I
print('I.assign_add')
I.assign_add([10, 10, 10, 10, 10])

I:
<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>
I.assing...
<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>
I again
<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>
I.assign_add


<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors and NumPy
Tensors can also be converted to NumPy arrays using:

* `np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype)
* `tensor.numpy()` - call on a tensor to convert to an ndarray

Doing this can be helpful: it makes tensors iterable & makes NumPy's methods available

In [154]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
print(f'J: {J}')
print(f'type of J: {type(J)}')
print(f'J.numpy: {J.numpy()}')
print(f'new type of J: {type(J.numpy())}')

J: [ 3.  7. 10.]
type of J: <class 'tensorflow.python.framework.ops.EagerTensor'>
J.numpy: [ 3.  7. 10.]
new type of J: <class 'numpy.ndarray'>


In [155]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Using `@tf.function`

Python functions might have the decorator [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function). For reference, [RealPython's guide on decorators](https://realpython.com/primer-on-python-decorators/). Decorators modify a function in one way or another.

In the `@tf.function` decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with `@tf.function`, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the [Better performnace with tf.function](https://www.tensorflow.org/guide/function) guide.

In [165]:
# Create a simple function
def timesTwoPlusY(x, y):
    return x ** 2 + y

x = tf.constant(np.arange(0, 10))
print(f'x: {x}')
print(f'y: {y}')
y = tf.constant(np.arange(10, 20))
print(timesTwoPlusY(x, y))

x: [0 1 2 3 4 5 6 7 8 9]
y: [10 11 12 13 14 15 16 17 18 19]
tf.Tensor([ 10  12  16  22  30  40  52  66  82 100], shape=(10,), dtype=int64)


In [166]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

2025-01-26 18:03:35.167675: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Checking access to GPUs
 [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).

In [167]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


If the above outputs an empty array (or nothing), it means you don't have access to a GPU (or at least TensorFlow can't find it).

If you're running in Google Colab, you can access a GPU by going to *Runtime -> Change Runtime Type -> Select GPU*.

## ToDo
Try following directions without code examples
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
2. Find the shape, rank and size of the tensors you created in 1
3. Create two tensors containing random values between 0 and 1 with shape [5, 300]
4. Multiply the two tensors you created in 3 using matrix multiplication
5. Multiply the two tensors you created in 3 using dot product
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
7. Find the min and max values of the tensor you created in 6
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value
10. One-hot encode the tensor you created in 9

In [206]:
# 1
vectorTest = tf.constant([2, 3])
matrixTest = matrix = tf.constant([[2, 3],[4, 5]])
scalarTest = tf.constant(2)

In [207]:
# 2
print('#2')
print('vector props:')
print(f'shape: {vectorTest.shape}')
print(f'rank: {tf.rank(vectorTest)}')
print(f'size: {tf.size(vectorTest)}')

print('')
print('matrix props:')
print(f'shape: {matrix.shape}')
print(f'rank: {tf.rank(matrix)}')
print(f'size: {tf.size(matrix)}')

print('')
print('scalar props:')
print(f'shape: {scalar.shape}')
print(f'rank: {tf.rank(scalar)}')
print(f'size: {tf.size(scalar)}')

#2
vector props:
shape: (2,)
rank: 1
size: 2

matrix props:
shape: (2, 2)
rank: 2
size: 4

scalar props:
shape: ()
rank: 0
size: 1


In [208]:

#3
print('')
print('#3: 2 random tensors')
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
randomTestOne = tf.random.uniform(shape=[5,300], minval=0, maxval=1)
randomTestTwo = tf.random.uniform(shape=[5,300], minval=0, maxval=1)
print(randomTestOne)
print(randomTestTwo)


#3: 2 random tensors
tf.Tensor(
[[0.803156   0.49777734 0.37054038 ... 0.42893624 0.49179256 0.39297235]
 [0.14517438 0.72666824 0.80103934 ... 0.832801   0.649397   0.29312778]
 [0.4216962  0.6768439  0.5627917  ... 0.56929183 0.90308595 0.31530714]
 [0.6198498  0.70206463 0.994668   ... 0.03745186 0.23192072 0.23984468]
 [0.01790595 0.40531397 0.5369972  ... 0.62693167 0.47887897 0.25383985]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.95831835 0.01680839 0.3156035  ... 0.67105925 0.76730955 0.20125735]
 [0.09921694 0.02475083 0.47242153 ... 0.9631474  0.34333456 0.8129494 ]
 [0.08817983 0.9311962  0.2293179  ... 0.41450226 0.008304   0.02438807]
 [0.54814565 0.37019622 0.5272658  ... 0.8656951  0.19644582 0.5959221 ]
 [0.8964087  0.15288067 0.3360591  ... 0.5725572  0.4094149  0.40059018]], shape=(5, 300), dtype=float32)


In [209]:

print('')
print('#4: matmul the 2 random tensors with matmul')
print(tf.matmul(randomTestOne, tf.transpose(randomTestTwo)))


#4: matmul the 2 random tensors with matmul
tf.Tensor(
[[70.66355  71.56842  77.197525 74.061646 73.22589 ]
 [72.29191  75.99317  82.135056 77.226845 77.29365 ]
 [67.8458   68.86569  76.16406  73.376366 73.11703 ]
 [68.15459  67.6496   76.78157  73.194916 71.7847  ]
 [70.889404 71.440285 77.61733  74.39659  72.28302 ]], shape=(5, 5), dtype=float32)


In [210]:

print('')
print('#5: multiply using dotproduct')
print(tf.tensordot(tf.transpose(randomTestOne), randomTestTwo, axes=1))


#5: multiply using dotproduct
tf.Tensor(
[[1.177087   0.6419784  0.7516079  ... 1.4004368  0.7987123  0.6665    ]
 [1.3569716  0.97849333 1.1619905  ... 2.1543193  0.9409194  1.2881734 ]
 [1.5107911  1.0004429  1.3293475  ... 2.4219928  0.9792701  1.5473644 ]
 ...
 [1.1264015  0.66765493 0.88978887 ... 1.7173007  0.88381606 1.0506966 ]
 [1.1717565  1.0243571  0.9523099  ... 1.8047764  0.8494368  0.97896916]
 [0.79249364 0.43507    0.54657596 ... 1.0296987  0.5558329  0.5696909 ]], shape=(300, 300), dtype=float32)


In [216]:
print('')
print('#6: random tensor with shape')
testSix = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
print(testSix)


#6: random tensor with shape
tf.Tensor(
[[[0.14241445 0.40161622 0.33360183]
  [0.6816542  0.69087017 0.22069418]
  [0.61336195 0.9588975  0.3314948 ]
  ...
  [0.21534526 0.8758553  0.90849984]
  [0.913136   0.3300879  0.21957576]
  [0.294909   0.51060224 0.41247094]]

 [[0.24516141 0.0526433  0.8009639 ]
  [0.39559937 0.91123044 0.66148484]
  [0.62018025 0.13185847 0.2584139 ]
  ...
  [0.69155025 0.35061288 0.7918345 ]
  [0.71887565 0.13187587 0.6776898 ]
  [0.91522217 0.72013485 0.5736792 ]]

 [[0.32997262 0.01919758 0.7673421 ]
  [0.37867343 0.09564745 0.07906318]
  [0.7100911  0.934427   0.5622425 ]
  ...
  [0.8063401  0.53997624 0.9590297 ]
  [0.7728716  0.5758432  0.53311133]
  [0.00398016 0.15231979 0.6468185 ]]

 ...

 [[0.3400538  0.40921474 0.04457414]
  [0.8624321  0.9367907  0.839291  ]
  [0.21796441 0.61002827 0.20527577]
  ...
  [0.48761916 0.46545267 0.9492396 ]
  [0.60848117 0.4233297  0.92878056]
  [0.5943769  0.86359346 0.43811893]]

 [[0.6843432  0.13533545 0.831674

In [218]:
print('')
print('#7: min & max of that tensor')
print(f'min: {tf.reduce_min(testSix)}')
print(f'max: {tf.reduce_max(testSix)}')


#7: min & max of that tensor
min: 4.172325134277344e-06
max: 0.9999963045120239


In [221]:
print('')
print('#8: random tensor & squeeze')
testEight = tf.random.uniform(shape=[1, 224, 224, 3])
print(f'testEight shape:{testEight.shape}')
print(f'testEight SQUEEZED:{tf.squeeze(testEight).shape}')


#8: random tensor & squeeze
testEight shape:(1, 224, 224, 3)
testEight SQUEEZED:(224, 224, 3)


In [226]:
print('')
print('#9: create with shape and custom vals')
my_values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # Replace these values with your own
testNine = tf.constant(my_values, shape=[10])
print(testNine)


#9: create with shape and custom vals
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


In [227]:
print('')
print('#10: one-hot-encode #9')
print(tf.one_hot(testNine, depth=len(testNine)))


#10: one-hot-encode #9
tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
